x-services-config: &commom-services-config
    networks:
        - backend-net
    environment:
        users-app-url: http://users-app:8000/api
        alarms-app-url: http://alarms-app:8000/api
        activation-service-url: http://activation-service:8000/api
        notification-service-url: http://notification-service:8000/api

services:
    # Databases
    users-db:
        image: postgres
        environment:
            POSTGRES_USER: "postgres"
            POSTGRES_PASSWORD: "password"
            POSTGRES_DB: "users"
        volumes:
            - users-db-data:/var/lib/postgresql/data
        networks:
            - users-net

    alarms-db:
        image: postgres
        environment:
            POSTGRES_USER: "postgres"
            POSTGRES_PASSWORD: "password"
            POSTGRES_DB: "alarms"
        networks:
            - alarms-net
        volumes:
            - alarms-db-data:/var/lib/postgresql/data

    # Apps
    users-app:
        <<: *commom-services-config
        build: 
            context: ./users
        volumes:
            - ./users/:/app
        networks:
            - backend-net
            - users-net
        ports:
            - "8000:8000"

    alarms-app:
        <<: *commom-services-config
        build: 
            context: ./alarms
        volumes:
            - ./alarms/:/app
        networks:
            - backend-net
            - alarms-net
        ports:
            - "8001:8000"

    # Services
    activation-service:
        <<: *commom-services-config
        build: 
            context: ./activation-service

    # Services
    notification-service:
        <<: *commom-services-config
        build: 
            context: ./notification-service

    # Exposed API Gateway
    api-gateway:
        <<: *commom-services-config
        build: 
            context: ./api-gateway
        ports:
            - "803:80"

networks:
    backend-net:
    users-net:
    alarms-net:

volumes:
    users-db-data:
    alarms-db-data:
