x-services-config: &commom-services-config
    networks:
        - backend-net
    environment:
        USERS_APP_URL: http://users-app:8000/api
        ALARMS_APP_URL: http://alarms-app:8000/api
        ACTIVATION_SERVICE_URL: http://activation-service:8000/api
        NOTIFICATION_SERVICE_URL: http://notification-service:8000/api

services:
    # Databases
    users-db:
        image: postgres
        environment:
            POSTGRES_USER: "postgres"
            POSTGRES_PASSWORD: "password"
            POSTGRES_DB: "users"
        volumes:
            - users-db-data:/var/lib/postgresql/data
        networks:
            - users-net

    alarms-db:
        image: postgres
        environment:
            POSTGRES_USER: "postgres"
            POSTGRES_PASSWORD: "password"
            POSTGRES_DB: "alarms"
        networks:
            - alarms-net
        volumes:
            - alarms-db-data:/var/lib/postgresql/data

    logs-db:
        image: mongo:4.0.4
        environment:
            MONGO_INITDB_ROOT_USERNAME: user
            MONGO_INITDB_ROOT_PASSWORD: password
        networks:
            - logs-net
        volumes:
            - logs-db-data:/data/db

    # Apps
    users-app:
        <<: *commom-services-config
        build: 
            context: ./users
        volumes:
            - ./users/:/app
        networks:
            - backend-net
            - users-net
        ports:
            - "8000:8000"

    alarms-app:
        <<: *commom-services-config
        build: 
            context: ./alarms
        volumes:
            - ./alarms/:/app
        networks:
            - backend-net
            - alarms-net
        ports:
            - "8001:8000"

    # Services
    activation-service:
        <<: *commom-services-config
        build: 
            context: ./activation-service

    notification-service:
        <<: *commom-services-config
        build: 
            context: ./notification-service

    logging-service:
        <<: *commom-services-config
        build: 
            context: ./logging-service
        environment:
            MONGO_CONN_STRING: mongodb://user:password@logs-db:27017/
        networks:
            - logs-net

    # Exposed API Gateway
    api-gateway:
        <<: *commom-services-config
        build: 
            context: ./api-gateway
        ports:
            - "803:80"

networks:
    backend-net:
    users-net:
    alarms-net:
    logs-net:

volumes:
    users-db-data:
    alarms-db-data:
    logs-db-data:
