
services:
    # Databases
    users-db:
        image: postgres
        environment:
            POSTGRES_USER: "postgres"
            POSTGRES_PASSWORD: "password"
            POSTGRES_DB: "users"
        ports:
            - "5430:5432"
        volumes:
            - users-db-data:/var/lib/postgresql/data
        networks:
            - users-net

    alarms-db:
        image: postgres
        environment:
            POSTGRES_USER: "postgres"
            POSTGRES_PASSWORD: "password"
            POSTGRES_DB: "alarms"
        networks:
            - alarms-net
        volumes:
            - alarms-db-data:/var/lib/postgresql/data

    # Apps
    users-app:
        build: 
            context: ./users
        volumes:
            - ./users/:/app
        networks:
            - backend-net
            - users-net
        ports:
            - "8000:8000"

    alarms-app:
        build: 
            context: ./alarms
        volumes:
            - ./alarms/:/app
        networks:
            - backend-net
            - alarms-net
        ports:
            - "8001:8000"

    # Exposed API Gateway
    api-gateway:
        build: 
            context: ./api-gateway
        ports:
            - "803:80"
        networks:
            - backend-net

networks:
    backend-net:
    users-net:
    alarms-net:

volumes:
    users-db-data:
    alarms-db-data:
