# Generated by Django 5.2.1 on 2025-06-07 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alarm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False)),
                ('title', models.TextField(max_length=60)),
                ('description', models.TextField(blank=True, max_length=120, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AlarmUser',
            fields=[
                ('pk', models.CompositePrimaryKey('alarm', 'user', blank=True, editable=False, primary_key=True, serialize=False)),
                ('user', models.PositiveIntegerField()),
                ('notify', models.BooleanField(default=True)),
                ('permission', models.CharField(choices=[('viewer', 'Can view alarm information and activity, but cannot make changes.'), ('editor', 'Can edit information from the alarm'), ('owner', 'Full control over the alarm. Including adding member and delete the alarm')], default='viewer', max_length=10)),
                ('alarm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.alarm')),
            ],
        ),
    ]
