# Generated by Django 5.2.1 on 2025-06-07 21:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alarmuser',
            name='alarm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alarm_users', to='core.alarm'),
        ),
    ]
