# Generated by Django 5.2.1 on 2025-06-09 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_alarmuser_alarm'),
    ]

    operations = [
        migrations.AddField(
            model_name='alarm',
            name='location',
            field=models.TextField(blank=True, max_length=60, null=True),
        ),
        migrations.CreateModel(
            name='MonitoringSpot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('alarm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitoring_spots', to='core.alarm')),
            ],
        ),
    ]
