# Generated by Django 5.2.1 on 2025-06-05 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=60, unique=True)),
                ('name', models.CharField(max_length=90)),
                ('email', models.CharField(max_length=90, unique=True)),
                ('cellphone', models.CharField(max_length=30, unique=True)),
            ],
        ),
    ]
